dist:
  name: otelcol-subtrace
  description: OpenTelemetry Collector with Subtrace Aggregator Processor
  output_path: ./otelcol-subtrace
  otelcol_version: 0.88.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.88.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.88.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.88.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.88.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.88.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.88.0
  - gomod: github.com/davidHaunschmied/otel-subtrace-demo/processor/subtraceaggregator v0.0.1

replaces:
  - github.com/davidHaunschmied/otel-subtrace-demo/processor/subtraceaggregator => ../processor/subtraceaggregator
